# Generated by Django 5.2.1 on 2025-05-18 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255, verbose_name="نام")),
                ("slug", models.SlugField(editable=False, max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="productions/",
                        verbose_name="عکس",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "رنگ",
                "verbose_name_plural": "رنگ ها",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                ("slug", models.SlugField(editable=False, max_length=255)),
                ("brand", models.CharField(max_length=255, verbose_name="برند")),
                (
                    "specifications",
                    models.CharField(max_length=255, verbose_name="مشخصات"),
                ),
                ("price", models.IntegerField(verbose_name="قیمت")),
                ("available", models.BooleanField(default=True, verbose_name="موجودی")),
                (
                    "main_image",
                    models.ImageField(upload_to="productionss/", verbose_name="عکس"),
                ),
                (
                    "secondary_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="productionss/",
                        verbose_name="عکس",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="productions.category",
                        verbose_name="دسته بندی",
                    ),
                ),
                (
                    "colors",
                    models.ManyToManyField(
                        to="productions.color", verbose_name="رنگ\u200cها"
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "photo",
                    models.ImageField(upload_to="productions/", verbose_name="عکس"),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="productions.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "عکس",
                "verbose_name_plural": "عکس ها",
            },
        ),
    ]
