# Generated by Django 5.2.1 on 2025-07-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255, verbose_name='نام اهداکننده')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('message', models.TextField(blank=True, null=True, verbose_name='پیام (اختیاری)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کمک مالی',
                'verbose_name_plural': 'کمک\u200cها',
            },
        ),
    ]
