# Generated by Django 5.2.1 on 2025-07-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='donate',
            field=models.BooleanField(default=False, verbose_name='اهدایی'),
        ),
    ]
